### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by ANIKET-SHIVAM** [pfalcon/graph-llvm-ir#3]
Hi, I getting an AssertionError(details below) on execution of the script. Could you please see on why is this happening. Thanks.

$ ./graph-llvm-ir ./vector_sum.ll && dot −Tpdf vector_sum.dot −o vector_sum.pdf

Error:
Traceback (most recent call last):
  File "./graph-llvm-ir", line 216, in <module>
    mod = Module.from_assembly(asm)
  File "/usr/local/lib/python2.7/dist-packages/llvm/core.py", line 443, in from_assembly
    return Module(m)
  File "/usr/local/lib/python2.7/dist-packages/llvm/**init**.py", line 16, in **init**
    assert ptr
AssertionError

**Comment by noraabiakar** [comment]
I have the same issue. Has it been solved?

**Comment by iGhoneim** [comment]
+1

**Comment by LlewellynVishal** [comment]
Hello,

I tried running your script for creating the CFG and DFG, but I keep getting an error while trying to parse the dot file to a pdf. I believe it's something to do with the way it is written out to the dot file. Did anyone else experience the same or knows any fix for it? Thanks in advance.

**Comment by LlewellynVishal** [comment]
I get the same assertion error on LLVM versions above 3.3. It works fine for llvm -3.3 though.

**Comment by mohmsslk** [comment]
I got the same error. solved yet?
